// Generated by scripts/gen-template.mjs from @meddleware/sui-token-template@1.0.6 — do not edit.
// Regenerate with `npm run gen:template` after bumping that package.

/** The compiled template module (base64), as published by `sui move build --build-env testnet`. */
export const TEMPLATE_MODULE_B64 =
  'oRzrCwcAAAUKAQAMAgweAyohBEsIBVNaB60B3QEIigNgBuoDVAq+BAUMwwQ6AA8BDgIGAgcCEAIRAAICAAEDBwACBAwBAAEDAAABAAEDAQwBAAEFBQIAAAoAAQABEgMEAAMJCAkBAAMLBgcBAgQMDQEBDAUNCgsAAwUCBQQMBA4CCAAHCAUAAgsEAQgACwIBCAABCgIBCAEBCAAHCQACCAEIAQgBCAEHCAUCCwMBCQALAgEJAAILAwEJAAcIBQELBAEJAAEGCAUBBQELAgEIAAIJAAUBCwQBCAATQ3VycmVuY3lJbml0aWFsaXplcgtNZXRhZGF0YUNhcBJTVUlfVE9LRU5fVEVNUExBVEUGU3RyaW5nC1RyZWFzdXJ5Q2FwCVR4Q29udGV4dARjb2luDWNvaW5fcmVnaXN0cnkLZHVtbXlfZmllbGQIZmluYWxpemUEaW5pdBVuZXdfY3VycmVuY3lfd2l0aF9vdHcPcHVibGljX3RyYW5zZmVyBnNlbmRlcgZzdHJpbmcSc3VpX3Rva2VuX3RlbXBsYXRlCHRyYW5zZmVyCnR4X2NvbnRleHQEdXRmOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIBCQoCEA9URU1QTEFURV9TWU1CT0wKAg4NVEVNUExBVEVfTkFNRQoCFRRURU1QTEFURV9ERVNDUklQVElPTgoCEhFURU1QTEFURV9JQ09OX1VSTAACAQgBAAAAAAIbCwAHAAcBEQEHAhEBBwMRAQcEEQEKATgADAMKATgBDAILAwoBLhEFOAILAgsBLhEFOAMCAAA='

/** How the module was built (the template package's `bytecode/build-info.json`). */
export const TEMPLATE_BUILD_INFO = Object.freeze({
  templateVersion: '1.0.6',
  toolchainVersion: '1.81.0',
  buildEnv: 'testnet',
  frameworkRev: '83f11dc85d5695a57894329b005b78d75f9bb059',
  sourceSha256: '58457c5b396899f1bea6f6975a823731eaf607b9ad3fb661f7944f7efcaa727b',
  moduleSha256: '41511ed4434e529c6ac47deb894ab6a93c6aef8c86417d103a730f825b7ae9b7',
} as const)

/** Identifiers compiled into the module (renamed at patch time). */
export const TEMPLATE_IDENTIFIERS = Object.freeze({
  module: 'sui_token_template',
  struct: 'SUI_TOKEN_TEMPLATE',
} as const)

/**
 * Constant-pool defaults the patcher replaces. Distinct on purpose: identical Move constants
 * deduplicate into one pool entry that could not be patched independently.
 */
export const TEMPLATE_DEFAULTS = Object.freeze({
  decimals: 9,
  symbol: 'TEMPLATE_SYMBOL',
  name: 'TEMPLATE_NAME',
  description: 'TEMPLATE_DESCRIPTION',
  iconUrl: 'TEMPLATE_ICON_URL',
} as const)
