// Generated by scripts/gen-template.mjs from @meddleware/sui-token-template@1.0.8 — do not edit.
// Regenerate with `npm run gen:template` after bumping that package.

/** The compiled template module (base64), as published by `sui move build --build-env testnet`. */
export const TEMPLATE_MODULE_B64 =
  'oRzrCwcAAAUKAQAMAgwkAzA4BGgQBXiGAQf+AakCCKcEYAaHBWQK6wUFDPAFgwEAFAETAgcCCAIVAhYAAwIAAQQHAAIADAEAAQIFDAEAAQMBAAEAAQMCDAEAAQUGAgAADAABAAANAgEAARcEBQACDwkKAQADChESAQADCxEBAQADDg8BAQADEAcIAQIEEQ4BAQwFEgsMAAcGAwYIDQYGCBAFBgQGCBMCCAAHCAYABQgAAwEBBwgGAgsEAQgACwMBCAABCgIBCAEBCAAHCQACCAEIAQgBCAEHCAYCCwQBCQALAwEJAAMHCwMBCQADBwgGAQsCAQkAAQYIBgEFAQsCAQgAAgkABQIHCwQBCQALAwEJAAELAwEIAAILBAEJAAcIBgELBQEJAAELBQEIAARDb2luE0N1cnJlbmN5SW5pdGlhbGl6ZXILTWV0YWRhdGFDYXASU1VJX1RPS0VOX1RFTVBMQVRFBlN0cmluZwtUcmVhc3VyeUNhcAlUeENvbnRleHQEY29pbg1jb2luX3JlZ2lzdHJ5C2R1bW15X2ZpZWxkCGZpbmFsaXplIGZpbmFsaXplX2FuZF9kZWxldGVfbWV0YWRhdGFfY2FwBGluaXQJaW5pdF93aXRoFm1ha2Vfc3VwcGx5X2ZpeGVkX2luaXQEbWludBVuZXdfY3VycmVuY3lfd2l0aF9vdHcPcHVibGljX3RyYW5zZmVyBnNlbmRlcgZzdHJpbmcSc3VpX3Rva2VuX3RlbXBsYXRlCHRyYW5zZmVyCnR4X2NvbnRleHQEdXRmOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgIBCQoCEA9URU1QTEFURV9TWU1CT0wKAg4NVEVNUExBVEVfTkFNRQoCFRRURU1QTEFURV9ERVNDUklQVElPTgoCEhFURU1QTEFURV9JQ09OX1VSTAMIB8qaOwAAAAABAQEBAQAAAgEJAQAAAAABBwsABwUHBgcHCwERAQIAAQAAAAMzCwAHAAcBEQIHAhECBwMRAgcEEQIKBDgADAYMBQoBBgAAAAAAAAAAJAQaDQYLAQoEOAEKBC4RCTgCCwIEIA0FCwY4AwUlCwYKBC4RCTgECwMEKwsFCwQ4BQUyCwUKBDgGCwQuEQk4BwIAAA=='

/** How the module was built (the template package's `bytecode/build-info.json`). */
export const TEMPLATE_BUILD_INFO = Object.freeze({
  templateVersion: '1.0.8',
  toolchainVersion: '1.81.0',
  buildEnv: 'testnet',
  frameworkRev: '83f11dc85d5695a57894329b005b78d75f9bb059',
  sourceSha256: 'a6bfae1eba108ca574eecd54cb595405573606aed500719cadd507c4565b3623',
  moduleSha256: '96298cca9c047e69dd1f168e6dcd071a5e5344b4edc917fb572dc33c49129630',
} as const)

/** Identifiers compiled into the module (renamed at patch time). */
export const TEMPLATE_IDENTIFIERS = Object.freeze({
  module: 'sui_token_template',
  struct: 'SUI_TOKEN_TEMPLATE',
} as const)

/**
 * Constant-pool defaults the patcher replaces. Distinct on purpose: identical Move constants
 * deduplicate into one pool entry that could not be patched independently.
 */
export const TEMPLATE_DEFAULTS = Object.freeze({
  decimals: 9,
  symbol: 'TEMPLATE_SYMBOL',
  name: 'TEMPLATE_NAME',
  description: 'TEMPLATE_DESCRIPTION',
  iconUrl: 'TEMPLATE_ICON_URL',
  initialSupply: 1000000007,
  fixedSupply: true,
  frozenMetadata: false,
} as const)
